# BSD 3-Clause License
# Copyright Â© 2022, GM Consult Pty Ltd
# All rights reserved.

name: hive_text_index
description: A Hive based InvertedIndex with AsyncCallbackIndexMixin.
version: 0.0.1-3
repository: https://github.com/GM-Consult-Pty-Ltd/hive_text_index
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/hive_text_index/issues


environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----
  collection: ^1.17.0
  gmconsult_dev: ^0.0.7
  hive: ^2.2.3
  rxdart: ^0.27.5
  text_indexing: ^0.22.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
